### ISSUE TITLE
Can CuPBoP be used by simply including the head files?

### ISSUE THREAD

**Issue by MiyaaL** [cupbop/CuPBoP#3]

**Comment by MiyaaL** [comment]
I want to use CuPBoP in some large project, which may have complicated Makefiles or CMakefiles and It may be very hard to figure out where to insert CuPBoP's logic. Is it possible to transform CuPBoP to some mode that only needs simply replace "#include <cuda_runtime.h>" with "#include "cudaRuntimeImpl.h"" and link some .so libraries?

**Comment by drcut** [comment]
Sorry for the late reply.

CuPBoP implements an IR-to-IR translation to translate compiled CUDA code (LLVM IR) to LLVM IR that can be executed on CPUs. Thus, we need to compile the CUDA and apply the transformation. These cannot be implemented by merely replace the head file.
