### ISSUE TITLE
Compile PyTorch with CuPBoP.

### ISSUE THREAD

**Issue by fengyuanyu1** [cupbop/CuPBoP#4]
Hi,  @drcut @hyesoon Excellent Work! Can I Compile PyTorch with CuPBoP?

**Comment by drcut** [comment]
Thanks for reaching out.
I think it is possible to do so, but there are some challenges which is indepdent with CuPBoP. Please correct me if I'm wrong.
First, some source code in PyTorch are automatically generated, thus, before building the PyTorch, these code is not existing, and we can only find them after the build process.
Second, also related with CUDA code, is that some kernels are generated at runtime (JIT), thus, we have to also integrate CuPBoP to the JIT process.

**Comment by fengyuanyu1** [comment]
>First, some source code in PyTorch are automatically generated, thus, before building the PyTorch, these code is not existing, and we can only find them after the build process. Second, also related with CUDA code, is that some kernels are generated at runtime (JIT), thus, we have to also integrate CuPBoP to the JIT process.

Right, we should generate these files previously by executing the codegen.py manually, then use the CuPBoP to compile them. Thx for your information.
